# Generated by Django 4.1.1 on 2022-12-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customer_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
