# Generated by Django 4.1.1 on 2022-12-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='article_images/')),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('publication_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
