# Generated by Django 4.1.1 on 2022-12-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tea_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='utensil_amount',
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
