# Generated by Django 4.1.1 on 2022-12-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tea_type",
            field=models.CharField(
                choices=[
                    ("Red", "Red"),
                    ("Black", "Black"),
                    ("Green", "Green"),
                    ("Oolong", "Oolong"),
                    ("Puer", "Puer"),
                    ("White", "White"),
                    ("Yellow", "Yellow"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
